### ISSUE TITLE
generate_joint_distribution() function not found

### ISSUE THREAD

**Issue by William-M-Ricardo** [nicolagnecco/erf-numerical-results#3]
---

### Issue: `generate_joint_distribution()` function not found

**Description:**

Hi, I encountered an issue while running the scripts from the project. I have successfully installed all the dependencies as outlined in the `dependencies.R` script, but I'm receiving an error that the function `generate_joint_distribution()` cannot be found.

Here is the error message:
```
Error in generate_joint_distribution(n, p, model = model, df = df, distr = distr): 
  could not find function "generate_joint_distribution"
```

**Steps to Reproduce:**
1. Ran the `dependencies.R` script to install all required packages.
2. Tried running the following code:
   ```r
   train_dat <- generate_joint_distribution(n, p, model = model, df = df, distr = distr)
   ```
3. The function `generate_joint_distribution()` is not recognized, leading to the above error.

**What I've tried:**
- I searched through the project files but couldn't find the function `generate_joint_distribution()` defined anywhere.
- I've confirmed that all dependencies are properly installed and loaded.

Could you please confirm whether this function is missing, or if I need to source a specific file that contains this function? Any guidance on how to resolve this issue would be much appreciated!

**System Information:**
- R version: [4.4.1]
- Operating system: [Windows]

Thank you in advance for your help!

**Comment by nicolagnecco** [comment]
Thanks for your message.

In the `dependencies.R` file, line 23 has 
```
# load local functions
purrr::map(here::here("R", list.files(here::here("R"))), source)
```

Did you also run that line?

This should import all function definitions in the `R` folder, including `R/model_functions.R/generate_joint_distribution`.

**Comment by William-M-Ricardo** [comment]
Thank you!
